<a href="https://colab.research.google.com/github/AlejandroJuarez98/MLEARNING20/blob/master/CL06_Introducci%C3%B3n_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**Introducción a TensorFlow**
> - TensorFlow es un marco de trabajo que contiene un conjunto de herramientas, reglas y patrones  que tiene el objetivo de facilitar la programación de algoritmos de deep learning. Su importancia:
>> - **Inclusión de AI.**
>> - **Abstracción de algoritmos complejos.**

**Módulos comunes en TensorFlow:**
> - **tf:** Funciones que facilitan las operaciones aritméticas, por ejemplo: **tf.abs, tf.add, tf.concat.**
> - **tf.error:** Errores de TF
> - **tf.data:** Funciones que implementan datasets
> - **tf.distributions:** Este módulo sirve para implementar funciones estadisticas.
> - **tf.io.gfile:** Implementa operaciones en archivos
> - **tf.image:** Implementa operaciones en imagines
> - **tf.keras:** Implementa las herramientas de Keras, para operaciones en redes neuronales.

**Conceptos:**
> - Tensor: Arreglo multidimensional.
> - Se compone de rangos. Ejemplo: tensor rango 0 (Escalar), Tensor rango 1 (1 dimensión), Tensor rango N (N dimensión).



- **Tensores constantes:**
```
  > - tf.constant ()
  > - tf.zeros ()
  > - tf.ones ()
  > - tf.fill ()
  > - tf.random ()
```

In [1]:
import tensorflow as tf

const_vector = tf.constant([[1,2,3,4]], shape=[2,2])
const_vector

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [6]:
print('Valor del vector: ', const_vector.numpy())
print('Tipo de valor: ', const_vector.dtype)
print('Dimensiones del vector constante: ', const_vector.shape)

Valor del vector:  [[1 2]
 [3 4]]
Tipo de valor:  <dtype: 'int32'>
Dimensiones del vector constante:  (2, 2)


In [9]:
zeros_vector = tf.zeros([4,4], dtype=tf.int32)
zeros_vector

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)>

In [14]:
fill_vector = tf.fill([2,3], 7)
fill_vector

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[7, 7, 7],
       [7, 7, 7]], dtype=int32)>

In [17]:
# Utilizando libreía tf.random
uniform_rvector = tf.random.uniform([5,5])
print(uniform_rvector, '\n')

normal_rvector = tf.random.normal([5,5])
print(normal_rvector, '\n')

tf.Tensor(
[[0.29061484 0.15357673 0.8518499  0.5153165  0.47954035]
 [0.7528684  0.09113455 0.66635585 0.47549665 0.751539  ]
 [0.61270595 0.29651606 0.44187272 0.24423563 0.75914633]
 [0.5189036  0.5527264  0.75890946 0.19811821 0.35717547]
 [0.8558171  0.20993602 0.91702485 0.8928088  0.8364612 ]], shape=(5, 5), dtype=float32) 

tf.Tensor(
[[ 1.2192106   1.1893235  -1.247736   -2.0378947   0.30907896]
 [-1.1091781  -1.0441334  -1.3731692   0.1337953   1.7150176 ]
 [ 0.87951946 -0.7464225  -0.879393    0.56090695  0.35950705]
 [-0.6727515  -0.04627789 -0.7344944  -0.30233243 -1.6000489 ]
 [ 1.9216613   1.167279    1.3410485   2.060293   -0.947742  ]], shape=(5, 5), dtype=float32) 



In [18]:
# Convertir lista de Python a Tensor
xlist = [1,2,3,4]
print (xlist, type(xlist))

xtensorlist = tf.convert_to_tensor(xlist, dtype=tf.int32)
xtensorlist

[1, 2, 3, 4] <class 'list'>


<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [28]:
# Variables de tipo tensor
tensor = tf.Variable(tf.ones([2,3]))
tensor

print('Values: ', tensor.read_value())

Values:  tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [29]:
tensor.assign([[1,3,4], [7,4,3]])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[1., 3., 4.],
       [7., 4., 3.]], dtype=float32)>

In [30]:
print('Valores del tensor: ', tensor)

Valores del tensor:  <tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 3., 4.],
       [7., 4., 3.]], dtype=float32)>


In [35]:
tensore = tf.random.normal([2,2,3,4])
tensore

<tf.Tensor: shape=(2, 2, 3, 4), dtype=float32, numpy=
array([[[[-1.015642  ,  0.15593393, -0.32311997,  0.57467973],
         [ 1.1702529 ,  0.75422066,  0.5403055 , -1.0234902 ],
         [-0.70500505, -0.91486603,  0.445015  ,  0.29868832]],

        [[-1.9918466 , -0.8445442 ,  0.54414207,  0.36607486],
         [-0.00991777,  1.1835113 , -0.72201747, -0.21298578],
         [ 0.7465507 , -0.12610039, -0.25020644, -0.8431239 ]]],


       [[[-0.02284714,  0.42925593, -0.09079198, -0.68230075],
         [ 0.7015925 ,  0.646014  , -0.55678326,  0.3860944 ],
         [-1.4883856 ,  0.22554728,  0.9340678 ,  0.06113051]],

        [[ 0.19820306, -0.00937879, -0.03273406, -0.17055546],
         [-0.47408223, -1.4352981 ,  0.44915602,  2.241759  ],
         [ 0.8331645 ,  2.7622385 ,  1.1225773 , -0.19420622]]]],
      dtype=float32)>

In [38]:
n = tf.constant([[3,4], [3,2]])
n1 = tf.constant([[1,2],[4,3]])

n1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 3]], dtype=int32)>

In [39]:
tf.add(n, n1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 6],
       [7, 5]], dtype=int32)>

In [42]:
tf.matmul(n, n1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 18],
       [11, 12]], dtype=int32)>